In [1]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [1]:
import torch

In [2]:
a=torch.tensor([5.],requires_grad=True)
b=torch.tensor([6.],requires_grad=True)

In [3]:
a

tensor([5.], requires_grad=True)

In [4]:
b

tensor([6.], requires_grad=True)

In [5]:
q = a**3 - b**2
q

tensor([89.], grad_fn=<SubBackward0>)

In [6]:
print(a.grad)

None


In [7]:
print(b.grad)

None


In [8]:
q.backward()

In [9]:
a.grad

tensor([75.])

In [10]:
b.grad

tensor([-12.])